
spring:
  main:
    allow-circular-references: true
  application:
    name: listit
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db4free.net:3306/songs_uem?allowPublicKeyRetrieval=true&useSSL=false
    username: devsongs123
    password: qwe123dfg
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    hibernate:
      ddl-auto: none
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5Dialect
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  flyway:
   baseline-on-migrate: true
   enabled: true
   locations: classpath:db/migration 
server:
  port: 8888
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
    
jwt:
  secret: bXktMzItY2hhcmFjdGVyLXVsdHJhLXNlY3VyZS1hbmQtdWx0cmEtbG9uZy1zZWNyZXQ=
  validate: 10800




